// <auto-generated by tools/gen-dialects.ts />
#nullable enable
using System.Collections.ObjectModel;
using InstrumentComponents.Kind;

namespace InstrumentComponents.Dialects;

public sealed class DialectProfile
{
    public required string Id { get; init; }
    public required InstrumentKind Kind { get; init; }
    public required string ManufacturerGlob { get; init; }
    public required string ModelGlob { get; init; }
    public required uint Channels { get; init; }
    public required IReadOnlyDictionary<string, string> Commands { get; init; }

    public string? Command(string key) => Commands.TryGetValue(key, out var v) ? v : null;

    public string? FormatCommand(string key, params (string Name, string Value)[] vars)
    {
        if (Command(key) is not { } tmpl) return null;
        foreach (var (name, value) in vars)
            tmpl = tmpl.Replace("{" + name + "}", value, StringComparison.Ordinal);
        return tmpl;
    }
}

public static class DialectRegistry
{
    public static readonly IReadOnlyList<DialectProfile> Profiles = new ReadOnlyCollection<DialectProfile>(new DialectProfile[]
    {
        new DialectProfile
        {
            Id = "generic_dmm",
            Kind = InstrumentKind.Dmm,
            ManufacturerGlob = "*",
            ModelGlob = "*",
            Channels = 1,
            Commands = new Dictionary<string, string>
            {
            ["measure_voltage_dc"] = ":MEAS:VOLT:DC?",
            ["measure_voltage_ac"] = ":MEAS:VOLT:AC?",
            ["measure_current_dc"] = ":MEAS:CURR:DC?",
            ["measure_current_ac"] = ":MEAS:CURR:AC?",
            ["measure_resistance_2w"] = ":MEAS:RES?",
            ["measure_resistance_4w"] = ":MEAS:FRES?",
            ["measure_temperature"] = ":MEAS:TEMP?",
            ["configure_voltage_dc"] = ":CONF:VOLT:DC",
            ["initiate"] = "INIT",
            ["fetch"] = "FETC?",
            ["read"] = "READ?",
            ["software_trigger"] = "*TRG"
            },
        },
        new DialectProfile
        {
            Id = "generic_dcpwr",
            Kind = InstrumentKind.DcPowerSupply,
            ManufacturerGlob = "*",
            ModelGlob = "*",
            Channels = 1,
            Commands = new Dictionary<string, string>
            {
            ["set_voltage"] = ":SOUR{channel}:VOLT {volts}",
            ["set_current_limit"] = ":SOUR{channel}:CURR {amps}",
            ["output_enable"] = ":OUTP{channel} {state}",
            ["output_state_query"] = ":OUTP{channel}?",
            ["read_voltage"] = ":MEAS:VOLT? {channel}",
            ["read_current"] = ":MEAS:CURR? {channel}",
            ["ovp_level"] = ":SOUR{channel}:VOLT:PROT {volts}",
            ["ovp_enable"] = ":SOUR{channel}:VOLT:PROT:STAT {state}",
            ["ovp_query"] = ":SOUR{channel}:VOLT:PROT:STAT?",
            ["sense_enable"] = ":OUTP{channel}:SENS {state}"
            },
        },
        new DialectProfile
        {
            Id = "generic_fgen",
            Kind = InstrumentKind.FunctionGenerator,
            ManufacturerGlob = "*",
            ModelGlob = "*",
            Channels = 1,
            Commands = new Dictionary<string, string>
            {
            ["set_waveform"] = ":SOUR:FUNC {scpi_name}",
            ["set_frequency"] = ":SOUR:FREQ {hz}",
            ["set_amplitude"] = ":SOUR:VOLT {vpp}",
            ["set_offset"] = ":SOUR:VOLT:OFFS {volts}",
            ["set_duty_cycle"] = ":SOUR:FUNC:SQU:DCYC {percent}",
            ["set_load"] = ":OUTP:LOAD {ohms}",
            ["output_enable"] = ":OUTP {state}",
            ["burst_count"] = ":SOUR:BURS:NCYC {count}",
            ["burst_state"] = ":SOUR:BURS:STAT {state}",
            ["burst_trigger"] = ":TRIG:SOUR {source}"
            },
        },
        new DialectProfile
        {
            Id = "generic_scope",
            Kind = InstrumentKind.Oscilloscope,
            ManufacturerGlob = "*",
            ModelGlob = "*",
            Channels = 4,
            Commands = new Dictionary<string, string>
            {
            ["set_timebase_scale"] = ":TIMebase:SCALe {seconds_per_div}",
            ["set_channel_scale"] = ":CHANnel{channel}:SCALe {volts_per_div}",
            ["channel_display"] = ":CHANnel{channel}:DISP {state}",
            ["channel_coupling"] = ":CHANnel{channel}:COUP {coupling}",
            ["trigger_source"] = ":TRIGger:EDGE:SOURce {source}",
            ["trigger_level"] = ":TRIGger:EDGE:LEVel {volts}",
            ["trigger_slope"] = ":TRIGger:EDGE:SLOPe {slope}",
            ["single"] = ":SINGle",
            ["run"] = ":RUN",
            ["stop"] = ":STOP",
            ["measure_vpp"] = ":MEASure:VPP? CHAN{channel}",
            ["measure_frequency"] = ":MEASure:FREQuency? CHAN{channel}",
            ["waveform_source"] = ":WAVeform:SOURce CHAN{channel}",
            ["waveform_format_ascii"] = ":WAVeform:FORMat ASCii",
            ["waveform_preamble"] = ":WAVeform:PREamble?",
            ["waveform_data"] = ":WAVeform:DATA?"
            },
        },
        new DialectProfile
        {
            Id = "generic_switch",
            Kind = InstrumentKind.Switch,
            ManufacturerGlob = "*",
            ModelGlob = "*",
            Channels = 1,
            Commands = new Dictionary<string, string>
            {
            ["close_route"] = ":ROUTe:CLOS (@({ch1},{ch2}))",
            ["open_route"] = ":ROUTe:OPEN (@({ch1},{ch2}))",
            ["is_closed"] = ":ROUTe:CLOS? (@({ch1},{ch2}))",
            ["open_all"] = ":ROUTe:OPEN:ALL"
            },
        },
        new DialectProfile
        {
            Id = "generic_counter",
            Kind = InstrumentKind.Counter,
            ManufacturerGlob = "*",
            ModelGlob = "*",
            Channels = 1,
            Commands = new Dictionary<string, string>
            {
            ["measure_frequency"] = ":MEASure:FREQuency?",
            ["measure_period"] = ":MEASure:PERiod?",
            ["reset_totalize"] = ":COUNter:CRESet",
            ["read_totalize"] = ":COUNter:DATA?",
            ["gate_time"] = ":SENSe:FREQuency:APERture {seconds}",
            ["channel_select"] = ":SENSe:FUNCtion:ON \\\"FREQ {channel}\\\""
            },
        },
        new DialectProfile
        {
            Id = "keysight_sensor",
            Kind = InstrumentKind.PowerMeter,
            ManufacturerGlob = "Keysight*",
            ModelGlob = "*U20*",
            Channels = 1,
            Commands = new Dictionary<string, string>
            {
            ["unit"] = ":UNIT:POW {unit}",
            ["auto_range"] = ":SENS:POW:RANG:AUTO {state}",
            ["auto_average"] = ":SENS:AVER:COUN:AUTO {state}",
            ["correction_frequency"] = ":SENS:FREQ {hz}",
            ["offset"] = ":SENS:CORR:GAIN2 {db}",
            ["initiate"] = "INIT",
            ["fetch"] = "FETC?",
            ["read"] = "READ?",
            ["configure"] = ":CONF"
            },
        },
        new DialectProfile
        {
            Id = "generic_pwrmeter",
            Kind = InstrumentKind.PowerMeter,
            ManufacturerGlob = "*",
            ModelGlob = "*",
            Channels = 1,
            Commands = new Dictionary<string, string>
            {
            ["unit"] = ":UNIT:POW {unit}",
            ["auto_range"] = ":SENS:POW:RANG:AUTO {state}",
            ["auto_average"] = ":SENS:AVER:COUN:AUTO {state}",
            ["correction_frequency"] = ":SENS:FREQ {hz}",
            ["offset"] = ":SENS:CORR:GAIN2 {db}",
            ["initiate"] = "INIT",
            ["fetch"] = "FETC?",
            ["read"] = "READ?",
            ["configure"] = ":CONF"
            },
        },
        new DialectProfile
        {
            Id = "keysight_xseries",
            Kind = InstrumentKind.SpectrumAnalyzer,
            ManufacturerGlob = "Keysight*",
            ModelGlob = "N90*",
            Channels = 1,
            Commands = new Dictionary<string, string>
            {
            ["center_frequency"] = ":FREQ:CENT {hz}",
            ["span"] = ":FREQ:SPAN {hz}",
            ["rbw"] = ":BAND {hz}",
            ["vbw"] = ":BAND:VID {hz}",
            ["ref_level"] = ":DISP:WIND:TRAC:Y:RLEV {dbm}",
            ["trace_data"] = ":TRAC:DATA? TRACE1",
            ["marker_peak"] = ":CALC:MARK:MAX",
            ["marker_x"] = ":CALC:MARK:X?",
            ["marker_y"] = ":CALC:MARK:Y?",
            ["sweep_continuous"] = ":INIT:CONT {state}",
            ["single_sweep"] = ":INIT:IMM",
            ["wait_opc"] = "*OPC?"
            },
        },
        new DialectProfile
        {
            Id = "rigol_dsa",
            Kind = InstrumentKind.SpectrumAnalyzer,
            ManufacturerGlob = "Rigol*",
            ModelGlob = "DSA*",
            Channels = 1,
            Commands = new Dictionary<string, string>
            {
            ["center_frequency"] = ":FREQ:CENT {hz}",
            ["span"] = ":FREQ:SPAN {hz}",
            ["rbw"] = ":BAND {hz}",
            ["vbw"] = ":BAND:VID {hz}",
            ["ref_level"] = ":DISP:WIND:TRAC:Y:RLEV {dbm}",
            ["trace_data"] = ":TRAC? TRACE1",
            ["marker_peak"] = ":CALC:MARK:MAX",
            ["marker_x"] = ":CALC:MARK:X?",
            ["marker_y"] = ":CALC:MARK:Y?",
            ["sweep_continuous"] = ":INIT:CONT {state}",
            ["single_sweep"] = ":INIT",
            ["wait_opc"] = "*OPC?"
            },
        },
        new DialectProfile
        {
            Id = "generic_specan",
            Kind = InstrumentKind.SpectrumAnalyzer,
            ManufacturerGlob = "*",
            ModelGlob = "*",
            Channels = 1,
            Commands = new Dictionary<string, string>
            {
            ["center_frequency"] = ":FREQ:CENT {hz}",
            ["span"] = ":FREQ:SPAN {hz}",
            ["rbw"] = ":BAND {hz}",
            ["vbw"] = ":BAND:VID {hz}",
            ["ref_level"] = ":DISP:WIND:TRAC:Y:RLEV {dbm}",
            ["trace_data"] = ":TRAC:DATA? TRACE1",
            ["marker_peak"] = ":CALC:MARK:MAX",
            ["marker_x"] = ":CALC:MARK:X?",
            ["marker_y"] = ":CALC:MARK:Y?",
            ["sweep_continuous"] = ":INIT:CONT {state}",
            ["single_sweep"] = ":INIT:IMM",
            ["wait_opc"] = "*OPC?"
            },
        },
    });

    static bool GlobMatch(string pat, string value)
    {
        value = value.ToLowerInvariant();
        pat = pat.ToLowerInvariant();
        if (pat == "*") return true;
        var starts = pat.StartsWith('*');
        var ends = pat.EndsWith('*');
        return (starts, ends) switch
        {
            (true, true) => pat.Length <= 2 || value.Contains(pat[1..^1], StringComparison.Ordinal),
            (false, true) => value.StartsWith(pat[..^1], StringComparison.Ordinal),
            (true, false) => value.EndsWith(pat[1..], StringComparison.Ordinal),
            _ => value == pat,
        };
    }

    public static DialectProfile Resolve(InstrumentKind kind, string? manufacturer = null, string? model = null)
    {
        var mfr = manufacturer ?? "";
        var mod = model ?? "";
        foreach (var profile in Profiles)
        {
            if (profile.Kind != kind) continue;
            if (GlobMatch(profile.ManufacturerGlob, mfr) && GlobMatch(profile.ModelGlob, mod))
                return profile;
        }
        return Profiles.First(p => p.Kind == kind && p.Id.StartsWith("generic_", StringComparison.Ordinal))
            ?? Profiles.First(p => p.Kind == kind);
    }
}
