// <auto-generated by tools/gen-shared-tables.ts />
namespace InstrumentComponents.Classes;

internal static class ScpiCommands
{
    public static string DmmMeasureVoltageDc(double? range) =>
        range is { } r ? $":MEAS:VOLT:DC? {r}" : ":MEAS:VOLT:DC?";

    public static string DmmMeasureVoltageAc(double? range) =>
        range is { } r ? $":MEAS:VOLT:AC? {r}" : ":MEAS:VOLT:AC?";

    public static string DmmMeasureCurrentDc(double? range) =>
        range is { } r ? $":MEAS:CURR:DC? {r}" : ":MEAS:CURR:DC?";

    public static string DmmMeasureCurrentAc(double? range) =>
        range is { } r ? $":MEAS:CURR:AC? {r}" : ":MEAS:CURR:AC?";

    public static string DmmMeasureResistance(double? range) =>
        range is { } r ? $":MEAS:RES? {r}" : ":MEAS:RES?";

    public static string DmmMeasureResistance2wire(double? range) =>
        range is { } r ? $":MEAS:RES? {r}" : ":MEAS:RES?";

    public static string DmmMeasureResistance4wire(double? range) =>
        range is { } r ? $":MEAS:FRES? {r}" : ":MEAS:FRES?";

    public static string DmmMeasureTemperature(double? range) =>
        range is { } r ? $":MEAS:TEMP? {r}" : ":MEAS:TEMP?";

    public static string DmmConfigureVoltageDc(double? range, double? resolution) => (range, resolution) switch
    {
        ({ } r, { } res) => $":CONF:VOLT:DC {r},{res}",
        ({ } r, null) => $":CONF:VOLT:DC {r}",
        (null, { } res) => $":CONF:VOLT:DC DEF,{res}",
        _ => ":CONF:VOLT:DC",
    };

    public static string DmmConfigureVoltageAc(double? range, double? resolution) => (range, resolution) switch
    {
        ({ } r, { } res) => $":CONF:VOLT:AC {r},{res}",
        ({ } r, null) => $":CONF:VOLT:AC {r}",
        (null, { } res) => $":CONF:VOLT:AC DEF,{res}",
        _ => ":CONF:VOLT:AC",
    };

    public static string DmmConfigureCurrentDc(double? range, double? resolution) => (range, resolution) switch
    {
        ({ } r, { } res) => $":CONF:CURR:DC {r},{res}",
        ({ } r, null) => $":CONF:CURR:DC {r}",
        (null, { } res) => $":CONF:CURR:DC DEF,{res}",
        _ => ":CONF:CURR:DC",
    };

    public static string DmmConfigureCurrentAc(double? range, double? resolution) => (range, resolution) switch
    {
        ({ } r, { } res) => $":CONF:CURR:AC {r},{res}",
        ({ } r, null) => $":CONF:CURR:AC {r}",
        (null, { } res) => $":CONF:CURR:AC DEF,{res}",
        _ => ":CONF:CURR:AC",
    };

    public static string DmmConfigureResistance(double? range, double? resolution) => (range, resolution) switch
    {
        ({ } r, { } res) => $":CONF:RES {r},{res}",
        ({ } r, null) => $":CONF:RES {r}",
        (null, { } res) => $":CONF:RES DEF,{res}",
        _ => ":CONF:RES",
    };

    public static string DmmConfigureResistance4wire(double? range, double? resolution) => (range, resolution) switch
    {
        ({ } r, { } res) => $":CONF:FRES {r},{res}",
        ({ } r, null) => $":CONF:FRES {r}",
        (null, { } res) => $":CONF:FRES DEF,{res}",
        _ => ":CONF:FRES",
    };

    public static string PsuSetVoltage(uint channel, double volts) => $":SOUR{channel}:VOLT {volts}";
    public static string PsuSetCurrentLimit(uint channel, double amps) => $":SOUR{channel}:CURR {amps}";
    public static string PsuOutputEnable(uint channel, bool enabled) => $":OUTP{channel} {(enabled ? "ON" : "OFF")}";
    public static string PsuOutputStateQuery(uint channel) => $":OUTP{channel}?";
    public static string PsuReadVoltage(uint channel) => $":MEAS:VOLT? {channel}";
    public static string PsuReadCurrent(uint channel) => $":MEAS:CURR? {channel}";
    public static string PsuOvpLevel(uint channel, double volts) => $":SOUR{channel}:VOLT:PROT {volts}";
    public static string PsuOvpEnable(uint channel, string state) => $":SOUR{channel}:VOLT:PROT:STAT {state}";
    public static string PsuOvpQuery(uint channel) => $":SOUR{channel}:VOLT:PROT:STAT?";
    public static string PsuSenseEnable(uint channel, string state) => $":OUTP{channel}:SENS {state}";
    public static string FgenSetWaveform(string scpiName) => $":SOUR:FUNC {scpiName}";
    public static string FgenSetFrequency(double hz) => $":SOUR:FREQ {hz}";
    public static string FgenSetAmplitude(double vpp) => $":SOUR:VOLT {vpp}";
    public static string FgenSetOffset(double volts) => $":SOUR:VOLT:OFFS {volts}";
    public static string FgenSetDutyCycle(double percent) => $":SOUR:FUNC:SQU:DCYC {percent}";
    public static string FgenSetLoad(double ohms) => $":OUTP:LOAD {ohms}";
    public static string FgenOutputEnable(bool enabled) => $":OUTP {(enabled ? "ON" : "OFF")}";
    public static string FgenBurstCount(uint count) => $":SOUR:BURS:NCYC {count}";
    public static string FgenBurstState(string state) => $":SOUR:BURS:STAT {state}";
    public static string FgenBurstTrigger(string source) => $":TRIG:SOUR {source}";
    public static string ScopeSetTimebaseScale(double secondsPerDiv) => $":TIMebase:SCALe {secondsPerDiv}";
    public static string ScopeSetChannelScale(uint channel, double voltsPerDiv) => $":CHANnel{channel}:SCALe {voltsPerDiv}";
    public static string ScopeChannelDisplay(uint channel, string state) => $":CHANnel{channel}:DISP {state}";
    public static string ScopeChannelCoupling(uint channel, string coupling) => $":CHANnel{channel}:COUP {coupling}";
    public static string ScopeTriggerSource(string source) => $":TRIGger:EDGE:SOURce {source}";
    public static string ScopeTriggerLevel(double volts) => $":TRIGger:EDGE:LEVel {volts}";
    public static string ScopeTriggerSlope(string slope) => $":TRIGger:EDGE:SLOPe {slope}";
    public static string ScopeMeasureVpp(uint channel) => $":MEASure:VPP? CHAN{channel}";
    public static string ScopeMeasureFrequency(uint channel) => $":MEASure:FREQuency? CHAN{channel}";
    public static string ScopeSetWaveformSource(uint channel) => $":WAVeform:SOURce CHAN{channel}";
    public static string SwitchCloseRoute(uint ch1, uint ch2) => $":ROUTe:CLOS (@({ch1},{ch2}))";
    public static string SwitchOpenRoute(uint ch1, uint ch2) => $":ROUTe:OPEN (@({ch1},{ch2}))";
    public static string SwitchIsClosed(uint ch1, uint ch2) => $":ROUTe:CLOS? (@({ch1},{ch2}))";
    public static string CounterGateTime(double seconds) => $":SENSe:FREQuency:APERture {seconds}";
    public static string CounterChannelSelect(uint channel) => ":SENSe:FUNCtion:ON \"FREQ " + channel + "\"";
    public static string PwrmeterUnit(string unit) => $":UNIT:POW {unit}";
    public static string PwrmeterAutoRange(string state) => $":SENS:POW:RANG:AUTO {state}";
    public static string PwrmeterAutoAverage(string state) => $":SENS:AVER:COUN:AUTO {state}";
    public static string PwrmeterCorrectionFrequency(double hz) => $":SENS:FREQ {hz}";
    public static string PwrmeterOffset(double db) => $":SENS:CORR:GAIN2 {db}";
    public static string SpecanCenterFrequency(double hz) => $":FREQ:CENT {hz}";
    public static string SpecanSpan(double hz) => $":FREQ:SPAN {hz}";
    public static string SpecanRbw(double hz) => $":BAND {hz}";
    public static string SpecanVbw(double hz) => $":BAND:VID {hz}";
    public static string SpecanRefLevel(double dbm) => $":DISP:WIND:TRAC:Y:RLEV {dbm}";
    public static string SpecanSweepContinuous(string state) => $":INIT:CONT {state}";

    public const string FgenReadFrequency = ":SOUR:FREQ?";
    public const string ScopeReadTimebaseScale = ":TIMebase:SCALe?";
    public const string ScopeRun = ":RUN";
    public const string ScopeStop = ":STOP";
    public const string ScopeSingle = ":SINGle";
    public const string ScopeWaveformFormatAscii = ":WAVeform:FORMat ASCii";
    public const string ScopeWaveformPreamble = ":WAVeform:PREamble?";
    public const string ScopeWaveformData = ":WAVeform:DATA?";
    public const string SwitchOpenAll = ":ROUTe:OPEN:ALL";
    public const string CounterMeasureFrequency = ":MEASure:FREQuency?";
    public const string CounterMeasurePeriod = ":MEASure:PERiod?";
    public const string CounterResetTotalize = ":COUNter:CRESet";
    public const string CounterReadTotalize = ":COUNter:DATA?";
    public const string DmmInitiate = "INIT";
    public const string DmmFetch = "FETC?";
    public const string DmmRead = "READ?";
    public const string DmmSoftwareTrigger = "*TRG";
    public const string PwrmeterInitiate = "INIT";
    public const string PwrmeterFetch = "FETC?";
    public const string PwrmeterRead = "READ?";
    public const string PwrmeterConfigure = ":CONF";
    public const string SpecanMarkerPeak = ":CALC:MARK:MAX";
    public const string SpecanMarkerX = ":CALC:MARK:X?";
    public const string SpecanMarkerY = ":CALC:MARK:Y?";
    public const string SpecanSingleSweep = ":INIT:IMM";
    public const string SpecanWaitOpc = "*OPC?";
    public const string SpecanTraceData = ":TRAC:DATA? TRACE1";
}
